config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, shallow: true
    resources :ingredients, shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy, inverse_of: :cocktail
  has_many :ingredients, through: :doses
  accepts_nested_attributes_for :doses
  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
    @cocktail.doses.build
  end

  def edit
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktails_path
    else
      render :edit
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    def cocktail_params
      params.require(:cocktail).permit(:name, :photo, doses_attributes: [:description, :ingredient_id])
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail.id)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail.id)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-inputs">
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div>
    <%= f.simple_fields_for :doses do |d| %>
      <%= d.association :ingredient %>
      <%= d.input :description %>
      <%= d.submit "Add a dose", class: "btn btn-primary" %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
<div class="container main-display">
<h1>Editing Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Show', @cocktail %> |
<%= link_to 'Back', cocktails_path %>
</div>

app/views/cocktails/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container main-display">

  <div class="cards">
    <% @cocktails.each do |cocktail| %>
      <div class="card"
        style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
        url('<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>')">
        <div class="card-category">
          <%= link_to cocktail.name, cocktail %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/cocktails/new.html.erb
<div class="container main-display">
<h1>New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>
</div>

app/views/cocktails/show.html.erb
<div class="container main-display">

  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @cocktail.name %>
  </p>

  <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

  <br>
  <br>

  <p>
    <strong>Doses:</strong>
    <ul>
      <% @cocktail.doses.each do |dose| %>
      <li>
        <%= dose.ingredient.name %> - 
        <%= dose.description %>
        <%= link_to "Delete", dose_path(dose), method: :delete,
        data: { confirm: "Delete ?"} %>
      </li>
      <% end %>
    </ul>
  </p>

  <p>
    <strong>Add another ingredient:</strong>
  </p>
  <%= simple_form_for [@cocktail, Dose.new] do |f| %>
    <%= f.association :ingredient %>
    <%= f.input :description %>
    <%= f.submit "Add a dose", class: "btn btn-primary" %>
  <% end %>

  <br>
  <br>
  
  <%= link_to 'Delete', cocktail_path(@cocktail), method: :delete, data: { confirm: "Delete ?" } %> | 
  <%= link_to 'Edit', edit_cocktail_path(@cocktail) %> |
  <%= link_to 'Back', cocktails_path %>

</div>

app/views/doses/new.html.erb
<br>
<br>
<h2>
  <%= link_to "Existed ingredient, please add another", cocktail_path(@dose.cocktail)%>
</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>

    <div class="banner">
      <div class="container">
        <h1>Misty taste of moonshine</h1>
        <p>Finisterre is the edge of everything known and familiar, a mysterious place.</p>
        <a href="/cocktails/new" class="btn-primary">Mix your own here!</a>
      </div>
    </div>

    <%= yield %>

    <div class="footer">
    <div class="links">
      <a href="#"><i class="fab fa-facebook-f"></i></a>
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
    </div>
    <p>Come make sexy misty fluffy drinks with us  <i class="fas fa-heart"></i></p>
  </div>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  
  </body>
</html>